config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root 'properties#index'
  get '/my_bookings', to: 'bookings#index'

  resources :properties do 
    resources :bookings
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ability.rb
class Ability
  # Add in CanCan's ability definition DSL
  include CanCan::Ability

  def initialize(user)
    return unless user.present? # additional permissions for logged in users (they can read their own posts)

    can :delete, Property, user: user
    can :update, Property, user: user
    can :create, Property, user: user

    can :create, Booking, user: user
    can :delete, Booking, user: user

    return unless user.admin? # additional permissions for administrators

    can :delete, Property
    can :update, Property
    can :create, Property
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :property, class_name: 'Property'

  validates :check_in, presence: true
  validates :check_out, presence: true
  validates :user, presence: true
  validates :property, presence: true
end

app/models/property.rb
class Property < ApplicationRecord
  has_many_attached :photos
  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings

  validates :name, presence: true, length: { in: 6..128 }
  validates :description, presence: true
  validates :address, presence: true
  validates :photos, presence: true, length: { in: 3..5, message: ' min 3 and max 5 for property' }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings, dependent: :destroy
  has_many :properties, through: :bookings

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true

  ROLES = %w[admin user].freeze
  def is?(requested_role)
    role == requested_role.to_s
  end

  def admin?
    is?('admin')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show destroy]
  before_action :authenticate_user!

  # GET /bookings or /bookings.json
  def index
    @bookings = Booking.where(user_id: current_user.id)
  end

  # GET /bookings/1 or /bookings/1.json
  def show; end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # POST /bookings or /bookings.json
  def create
    @booking = Booking.new(check_in: params[:check_in], check_out: params[:check_out],
                           property_id: params[:property_id])
    @booking.user_id = current_user.id

    respond_to do |format|
      if @booking.save
        format.html { redirect_to property_bookings_path, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1 or /bookings/1.json
  def destroy
    @booking.destroy

    respond_to do |format|
      format.html { redirect_to property_bookings_path, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_booking
    @booking = Booking.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def booking_params
    params.require(:booking).permit(:check_in, :check_out, :property_id)
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: %i[show edit update destroy]

  # GET /properties or /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1 or /properties/1.json
  def show
    @cover = @property.photos[2]
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit; end

  # POST /properties or /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to property_url(@property), notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1 or /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to property_url(@property), notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1 or /properties/1.json
  def destroy
    @property.destroy

    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_property
    @property = Property.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def property_params
    params.require(:property).permit(:name, :description, :address, photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/bookings/_booking.html.erb
<div id="<%= dom_id booking %>" class="h-max">
  <div>
    <% cover = Property.find_by(id: booking.property_id).photos[2] %>
    <div><%= image_tag(cover,class: "object-content xl:object-cover w-full h-56 rounded-md" ) %></div>
    <article class="flex flex-col justify-center py-3 pl-3 h-full min-h-[120px]">
      <h4 class="mb-3 text-xl font-bold tracking-tight text-gray-800 mb-0">
        From: <%= booking.check_in %> at 1PM
      </h4>
      <h4 class="mb-3 text-xl font-bold tracking-tight text-gray-800 mb-0">
        To: <%= booking.check_out %> at 12PM
      </h4>
    </article>
  </div>
</div>

app/views/bookings/_form.html.erb
<%= form_with :url => "/properties/#{params[:property_id]}/bookings",:html =>
{:class =>'bg-white w-[300px] md:w-[500px] lg:w-[700px] min-h-[400px] p-5
rounded-xl flex flex-col justify-center gap-4'}, :method => :post do |form| %>
<% if booking.errors.any? %>
<div style="color: red">
  <h2>
    <%= pluralize(booking.errors.count, "error") %> prohibited this booking from
    being saved:
  </h2>

  <ul>
    <% booking.errors.each do |error| %>
    <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div>
  <%= form.label :check_in, style: "display: block", class: "text-sm
  text-gray-600" %> <%= form.date_field :check_in, class: "w-full h-10 px-3 mb-2
  text-base text-gray-700 placeholder-gray-600 border rounded-lg
  focus:shadow-outline" %>
</div>

<div>
  <%= form.label :check_out, style: "display: block", class: "text-sm
  text-gray-600" %> <%= form.date_field :check_out, class: "w-full h-10 px-3 mb-2
  text-base text-gray-700 placeholder-gray-600 border rounded-lg
  focus:shadow-outline" %>
</div>

<div><%= form.submit  class: "w-full h-12 px-6 text-white
  transition-colors duration-150 bg-black rounded-lg focus:shadow-outline
  hover:bg-gray-800 cursor-pointer" %></div>
<% end %>

app/views/bookings/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="pt-[80px] flex flex-col ">
  <h1 class="text-center text-xl">
    You have <strong><%= @bookings.length%></strong> bookings
  </h1>
  <div
    class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 py-5 gap-3 auto-rows-auto items-center w-full px-3"
  >
    <% @bookings.each do |booking| %>
    <div
      id="bookings"
      class="w-full h-full overflow-hidden rounded-lg shadow-lg p-5 flex flex-col justify-between bg-white"
    >
      <%= render booking %>
      <a>
        <%= link_to "Show this booking", property_booking_path(id: booking.id, property_id: booking.property_id),
        class: "w-full h-12 py-3 text-white text-center transition-colors
        duration-150 bg-black rounded-full focus:shadow-outline
        hover:bg-gray-800 cursor-pointer" %>
      </a>
    </div>
    <% end %>
  </div>
  <div class="flex flex-col md:flex-row justify-center gap-3">
    <a
      ><%= link_to "Back to properties", properties_path, class: "font-bold
      text-center self-center underline underline-offset-8 pb-5" %></a
    >
  </div>
</div>

app/views/bookings/new.html.erb
<div
  class="flex flex-col justify-center items-center bg-gray-100 gap-3 h-screen"
>
  <div class="flex flex-col justify-center items-center pt-32 bg-gray-100">
    <h2
      class="mb-3 text-2xl font-bold tracking-tight text-gray-800 text-center"
    >
      New booking
    </h2>

    <%= render "form", booking: @booking %>

    <br />

    <div class="flex flex-col mt-3 gap-3 justify-center items-center">
      <%= link_to "Back to bookings", property_bookings_path, class: "underline
      underline-offset-4 font-bold" %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="h-auto w-full flex flex-col pt-[70px] items-center ">
  <div class="w-4/6 p-4 rounded-lg bg-white"><%= render @booking %>
 <div class="px-2"> 
   <label class="text-md font-semibold ">Property: </label>
  <p>
   <%= Property.find_by(id:@booking.property_id).name %> 
  </p>
  <label class="text-md font-semibold ">Located at: </label>
  <p>
     <%= Property.find_by(id:@booking.property_id).address %>
  </p>
  <label class="text-md font-semibold ">Any further info or notices will be directed to: </label>
  <p>
    <%=
    User.find_by(id: current_user.id).email %>
  </p>
</div>
<div class="link flex flex-col md:flex-row justify-around items-center py-4 ">
    <%= link_to "Back to bookings", property_bookings_path, class:" pt-2 h-10 px-5 m-2 text-blue-100 transition-colors duration-150 bg-blue-600 rounded-lg focus:shadow-outline hover:bg-blue-700"  %> 
    <%= button_to "Cancel this booking", property_booking_url(property_id:@booking.property_id, id: @booking.id), method: :delete, class: 'h-10 px-5 m-2 text-red-100 transition-colors duration-150 bg-red-700 rounded-lg focus:shadow-outline hover:bg-red-800' %>
  </div>
</div>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PropertyExhibit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class='bg-gray-200'>
   <p class="notice text-center bg-green-100 text-gray-400 rounded-lg"><%= notice %></p>
   <p class="alert text-center bg-red-100 text-gray-400 rounded-lg"><%= alert %></p>
    <div class = 'fixed w-full h-[70px] flex justify-between items-center px-4 bg-white shadow-md'>
      <div>
       <img src="https://user-images.githubusercontent.com/92399469/196821880-2e5fbb38-5342-40af-8753-362bef90d02c.png" class="hidden md:block w-[60px] rounded-md" />
      </div>
     <div class='flex gap-4'>
         <% if current_user %>
           <div class='font-normal text-sm sm:text-md text-gray-700 pr-10'> <%= button_to "log out", destroy_user_session_path, method: :delete %> </div>
         <% else %>
           <div class='font-normal text-sm sm:text-md text-gray-700 pr-10'> <%= button_to "Login",  new_user_session_path, method: :get %></div>
         <% end %>
         <div class='font-normal text-sm sm:text-md text-gray-700 pr-10'> <%= button_to "Properties", properties_path, method: :get %> </div>
          <div class="font-normal text-sm sm:text-md text-gray-700 pr-10">
          <%= button_to "My Bookings", my_bookings_path, method: :get %>
        </div>
      </div>
    </div>
  
    <%= yield %>
  </body>
</html>

app/views/properties/_form.html.erb
<%= form_with(model: property, :html => {:class =>'bg-white w-[300px]
md:w-[600px] lg:w-[800px] min-h-[450px] p-5 rounded-xl flex flex-col
justify-center gap-4'}) do |form| %> <% if property.errors.any? %>
<div
  class="flex flex-col justify-center items-center bg-red-100 rounded-lg text-red-800"
>
  <h2>
    <%= pluralize(property.errors.count, "error") %> prohibited this property
    from being saved:
  </h2>

  <ul>
    <% property.errors.each do |error| %>
    <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div>
  <%= form.label :name, style: "display: block", class: "text-sm text-gray-600"
  %> <%= form.text_field :name, class: "w-full h-10 px-3 mb-2 text-base
  text-gray-700 placeholder-gray-600 border rounded-lg focus:shadow-outline" %>
</div>

<div>
  <%= form.label :description, style: "display: block", class: "text-sm
  text-gray-600" %> <%= form.text_area :description, class: "w-full h-10 px-3
  mb-2 text-base text-gray-700 placeholder-gray-600 border rounded-lg
  focus:shadow-outline" %>
</div>

<div>
  <%= form.label :address, style: "display: block", class: "text-sm
  text-gray-600" %> <%= form.text_area :address, class: "w-full h-10 px-3 mb-2
  text-base text-gray-700 placeholder-gray-600 border rounded-lg
  focus:shadow-outline" %>
</div>

<div>
  <%= form.label :photos, style: "display: block", class: "text-sm
  text-gray-600" %> <%= form.file_field :photos, class: "w-full h-10 px-3 mb-2
  text-base text-gray-700 placeholder-gray-600 border rounded-lg
  focus:shadow-outline p-1", multiple: true %>
</div>

<div>
  <%= form.submit  class: "w-full h-12 px-6 text-white
  transition-colors duration-150 bg-black rounded-lg focus:shadow-outline
  hover:bg-gray-800 cursor-pointer" %>
</div>
<% end %>

app/views/properties/_property.html.erb
<div id="<%= dom_id property %>" class='h-max' >
  <div class="">
   <% if @cover %>
    <div class=''> <%= image_tag(@cover,class: "object-content w-full max-h-[60vh] " ) %> </div>
    <% else %>
    <div class="w-full h-max overflow-x-scroll whitespace-nowrap scroll-smooth scrollbar-hide flex h-80 w-full rounded-xl ">
    <% property.photos.each do |photo| %>
    <%= image_tag(photo,class: "object-cover w-full h-[100%] " ) %> 
    <% end %>
     <% end %>
    </div>
    <% if @cover %>
    <article class=" pl-10 md:pl-32 flex flex-col  py-[10vw] gap-5 h-full min-h-[120px]">
    <% else %>
    <article class="flex flex-col justify-between py-3 h-full min-h-[120px]">
    <% end %>
    <p class="leading-normal text-gray-500 text-sm">
    <%= property.description %></p>
    <h4 class="mb-3 text-xl font-bold tracking-tight text-gray-800 mb-0"><%= property.name %></h4>
    <p class="leading-normal text-gray-500 text-sm">
    <%= property.address %></p>
    </article>
  </div>
</div>

app/views/properties/edit.html.erb
<div
  class="flex flex-col justify-center items-center bg-gray-100 gap-3 h-screen"
>
  <div class="flex flex-col justify-center items-center pt-32 bg-gray-100">
    <h2
      class="mb-3 text-2xl font-bold tracking-tight text-gray-800 text-center"
    >
      Editing property
    </h2>

    <%= render "form", property: @property %>

    <br />

    <div class="flex flex-col mt-3 gap-3 justify-center items-center">
      <%= link_to "Show this property", @property, class: "underline
      underline-offset-4 font-bold" %> <%= link_to "Back to properties",
      properties_path, class: "underline underline-offset-4 font-bold" %>
    </div>
  </div>
</div>

app/views/properties/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="pt-[80px] flex flex-col">
  <h1 class="text-center text-xl">
    Find what suits you within our
    <strong><%= @properties.length%></strong> properties
  </h1>

  <div
    class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 py-5 gap-3 auto-rows-auto items-center w-full px-3"
  >
    <% @properties.each do |property| %>
    <div
      id="properties"
      class="w-full h-full overflow-hidden rounded-lg shadow-lg p-5 flex flex-col justify-between bg-white"
    >
      <%= render property %> <%= link_to "Show this property", property, class:
      "w-full h-12 py-3 text-white text-center transition-colors duration-150
      bg-black rounded-full focus:shadow-outline hover:bg-gray-800
      cursor-pointer" %>
    </div>
    <% end %>
  </div>

  <% if @properties.length < 50 %>

  <!-- only user can add a new property -->
  <% if can? :create, Property %>
  <button
    class="font-bold text-center self-center underline underline-offset-8 pb-5"
  >
    <%= link_to "Add a new property", new_property_path %>
  </button>
  <% else %>
  <p class="text-sm bg-green-50 text-center pb-5">
    Please Sign-in or Sign-up to be able to add your property for rentals and to
    be able to book a property
  </p>
  <% end %> <% else %>
  <h5 class="text-center">
    The number of properties is limited to <strong>50</strong>
  </h5>
  <% end %>
</div>

app/views/properties/new.html.erb
<div
  class="flex flex-col justify-center items-center bg-gray-100 gap-3 h-screen"
>
  <div class="flex flex-col justify-center items-center pt-32 bg-gray-100">
    <h2
      class="mb-3 text-2xl font-bold tracking-tight text-gray-800 text-center"
    >
      New property
    </h2>

    <%= render "form", property: @property %>

    <br />

    <div class="flex flex-col mt-3 gap-3 justify-center items-center">
      <%= link_to "Back to properties", properties_path, class: "underline
      underline-offset-4 font-bold" %>
    </div>
  </div>
</div>

app/views/properties/show.html.erb
<p style="color: green"><%= notice %></p>
<div class='h-[70px] w-full'></div>
<%= render @property %>
<div class="info pl-10 md:pl-32 flex flex-col gap-5">
<span>
    <h5 class="text-lg font-semibold">We offer</h5>
    <ul class="list-disc px-7">
      <li> Free cancellation on nearly all units.</li>
      <li> Clear pricing with no hidden fees.</li>
      <li> Book properties on the move.</li>
      <li> Your loyalty rewarded with freebies, perks and discounts.</li>
      <li> Price match guarantee.</li>
      <li> Wide range of choices different level properties.</li>
  </ul>
  </span>
  <span>
    <h5 class="text-lg font-semibold">General Rules & Regulations</h5>
    <ul class="list-disc px-7">
      <li> Check-in at 14.00 hrs. and Check-out 11.00 hrs.</li>
      <li> Exceeding check-out time, during 13.00 – 16.00 hrs., will result in extra charge at 50% of room rate.</li>
      <li> Full night charge of an extra night shall be applied to the check-out done later than 16.00 hrs.</li>
      <li>The rooms, lobby or common areas of the residence may not be used for any business purposes, or for any purpose apart from accommodation, without the express permission of the residence.</li>
      <li>Please do not hang any items or objects whatsoever from the windows of your guest room.</li>
      <li>The residence allocates space to offer guests the convenient parking; but does not cover any costs
          associated with any damages or missing property occurring to the vehicle.
      </li>
    </ul>
  </span>
  <span>
    <h5 class="text-lg font-semibold">Safety & Security Rules & Regulations</h5>
    <p class="font-semibold pl-2">Please do not bring onto the premises of the residence any of the following:</p>
    <ul class="list-disc px-8">
      <li> Animals or birds of any kind, except service animals.</li>
      <li> Gunpowder, oils or other explosives or inflammables.</li>
      <li> Objects emitting a foul odor.</li>
      <li> Unregistered firearms or swords.</li>
      <li>Objects of an unusually large size or in unusually large quantities</li>
      <li>Illegal drugs or other articles, the possession of which is prohibited by the law.</li>
  </ul>
  </span>
</div>
<!-- a visitor can not edit, delete a property, nor create a booking without sign-in -->
<div class=' flex flex-col md:flex-row gap-4 justify-center p-5'>
  <button class='back h-12 underline underline-offset-8 text-sm  px-5 m-2 border-solid border-[1px]  text-gray-800 transition-colors duration-150  rounded-lg focus:shadow-outline hover:text-[1.5vw]'>
    <%= link_to "Back to properties ",properties_path %>
  </button>
  <button class='h-12 underline underline-offset-8 text-sm  px-5 m-2 border-solid border-[1px]  text-gray-800 transition-colors duration-150  rounded-lg focus:shadow-outline hover:text-[1.5vw]'>
    <%= link_to "Edit this property", edit_property_path(@property) if can? :update, Property %>
  </button>
  <button class='book h-12 underline underline-offset-8 text-sm  px-[] m-2 border-solid border-[1px]  text-gray-800 transition-colors duration-150  rounded-lg focus:shadow-outline hover:text-[1.5vw]'>
    <%= link_to "Book this property", new_property_booking_path(@property.id) if can? :create, Booking %>
  </button>
  <% if can? :delete, Property %>
  <%= button_to "Delete this property", @property, method: :delete, class: 'text-sm h-12 underline underline-offset-8 px-5 m-2 border-solid border-[1px]  text-gray-800 transition-colors duration-150  rounded-lg focus:shadow-outline hover:bg-red-400' %>
  <% end %>
</div>

  